### PR TITLE
feat: symfony 7

### PR DESCRIPTION
**Pull request by k0d3r1s**
Added symfony 7 support, will test more and check if everything works. Fixes: #130  

comments are welcome :)

P.S. Used @musahaidari PR #128 as a base as there are already a lot of things fixed

### CODE REVIEW

**Comment by SoufianLagnaoui** [comment]
@k0d3r1s  you forgot to add attributes to the entities instead of annotations

**Comment by k0d3r1s** [comment]
@SoufianLagnaoui that is more like doctrine thing (as annotations still do work here) but sure, can fix that too

**Comment by k0d3r1s** [comment]
@SoufianLagnaoui fix that.  
now i'm quite not sure yet if only switching annotations to attributes fix this issue: #132 . or there should be dependency change from doctrine bundle to specifically depend on orm/dbal

**Comment by SoufianLagnaoui** [comment]
@k0d3r1s i m pretty sure it will resolve the issue

**Comment by NoUseFreak** [comment]
Thanks for the contribution!

**Pull request merged**
